services:
  - type: web
    name: ansapra
    env: python
    region: singapore
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PORT
        value: 10000
      - key: SECRET_KEY
        generateValue: true
      - key: DEEPSEEK_API_KEY
        sync: false
      - key: SPRINGER_API_KEY
        sync: false
    autoDeploy: true
